#ifndef ECL_WEB_CONFIG_HPP
#define ECL_WEB_CONFIG_HPP

#ifndef   ECL_WEB_CONFIG_CACHE_SIZE
#  define ECL_WEB_CONFIG_CACHE_SIZE    2048
#endif // ECL_WEB_CONFIG_CACHE_SIZE

#ifndef   ECL_WEB_CONFIG_HEADERS_COUNT
#  define ECL_WEB_CONFIG_HEADERS_COUNT 32
#endif // ECL_WEB_CONFIG_HEADERS_COUNT

#endif // ECL_WEB_CONFIG_HPP
